apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: clo835
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: flask-container
        image: 638733641367.dkr.ecr.us-east-1.amazonaws.com/clo835:flask
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBHOST
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBPORT
        - name: HEADER_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: NAME
        - name: IMAGENAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: IMAGENAME
        - name: BUCKET
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: BUCKET
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SESSION_TOKEN
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_DEFAULT_REGION

